spring:
  application:
    name: Test1221Systems
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test1221System
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 280305
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8045
