version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    networks:
      - network

  backend:
    image: openjdk:21
    container_name: spring-backend
    depends_on:
      - postgres
    volumes:
      - ./Test1221Systems-0.0.1-SNAPSHOT.jar:/app/backend.jar
    working_dir: /app
    command: ["java", "-jar", "backend.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_FLYWAY_ENABLED: "true"
    ports:
      - "8045:8045"
    networks:
      - network

networks:
  network:
    driver: bridge